# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EveractiveCli < Formula
  desc "CLI for the Everactive IoT Platform"
  homepage "https://everactive.com"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.2/everactive-cli_Darwin_arm64.tar.gz"
      sha256 "3b74b89daef547f571d6cb18a85372a51d4b82622f37f42d5d2822574f5fc3fa"

      def install
        bin.install "everactive-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.2/everactive-cli_Darwin_x86_64.tar.gz"
      sha256 "b44ed1807ba32d2caf50034c6b9a8ba2981268ec826c54b9c711e4cb12658e0f"

      def install
        bin.install "everactive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.2/everactive-cli_Linux_arm64.tar.gz"
      sha256 "0e042dce17c0d482279aac023a445fdeb284646c082a4614213096d4639fd413"

      def install
        bin.install "everactive-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.2/everactive-cli_Linux_x86_64.tar.gz"
      sha256 "3ff77013c8f1d26fcdcd54a9f0f3f02edf254dc6accc4b05b030da0dc88df969"

      def install
        bin.install "everactive-cli"
      end
    end
  end
end
