# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EveractiveCli < Formula
  desc "CLI for the Everactive IoT Platform"
  homepage "https://everactive.com"
  version "0.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.4/everactive-cli_Darwin_arm64.tar.gz"
      sha256 "05807a7594ef18864ef677ffe56b793a7e3071892bd5ecb112c9ecc6cf4850a7"

      def install
        bin.install "everactive-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.4/everactive-cli_Darwin_x86_64.tar.gz"
      sha256 "d0232b369db7e2f17e482f11744ce8199082d1c77bedc18e98bcb9330c049512"

      def install
        bin.install "everactive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.4/everactive-cli_Linux_arm64.tar.gz"
      sha256 "4bf74056ee0eda704647e858d4b4f2ed267139628250bff94ffe9be9dfe94d5b"

      def install
        bin.install "everactive-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.4.4/everactive-cli_Linux_x86_64.tar.gz"
      sha256 "2eaed6398b67c7f4b8201ce7fed6b08750485bc6293be1e1a814a8fefc83d81a"

      def install
        bin.install "everactive-cli"
      end
    end
  end
end
