# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EveractiveCli < Formula
  desc "CLI for the Everactive IoT Platform"
  homepage "https://everactive.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.5.0/everactive-cli_Darwin_arm64.tar.gz"
      sha256 "3ebff4fdd85d551cb95c8f528aae03cbb19ba0e12b4a0d441dcf02b96745eac6"

      def install
        bin.install "everactive-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.5.0/everactive-cli_Darwin_x86_64.tar.gz"
      sha256 "c9465a3776d6509ac7dfefe276133e5b44b00b3fb4530390a9a7670abc4ab341"

      def install
        bin.install "everactive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.5.0/everactive-cli_Linux_arm64.tar.gz"
      sha256 "2eee21b98060aa9860c923d56016feeb3c824ece3d966daba54c2da4e3e4646e"

      def install
        bin.install "everactive-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/everactive/everactive-cli/releases/download/v0.5.0/everactive-cli_Linux_x86_64.tar.gz"
      sha256 "cee30c34cad65d058d59a0458e3282477c547d78d2efd77f708171a406e8b82e"

      def install
        bin.install "everactive-cli"
      end
    end
  end
end
